/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogCard: typeof import('./components/BlogCard/index.vue')['default']
    CatalogCard: typeof import('./components/CatalogCard/index.vue')['default']
    CatalogItem: typeof import('./components/CatalogCard/CatalogItem/index.vue')['default']
    ChannelCard: typeof import('./components/ChannelCard/index.vue')['default']
    CutomBtn: typeof import('./components/CutomBtn.vue')['default']
    DIalogCard: typeof import('./components/DIalogCard/index.vue')['default']
    LanguageSwitch: typeof import('./components/LanguageSwitch/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfInfoCard: typeof import('./components/SelfInfoCard/index.vue')['default']
    Tag: typeof import('./components/Tag/index.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch/index.vue')['default']
    WeatherCard: typeof import('./components/WeatherCard/index.vue')['default']
    ZBtn: typeof import('./components/ZBtn/index.vue')['default']
  }
}
