/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChannelCard: typeof import('./components/ChannelCard/index.vue')['default']
    LanguageSwitch: typeof import('./components/LanguageSwitch/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./components/Tag/index.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch/index.vue')['default']
    WeatherCard: typeof import('./components/WeatherCard/index.vue')['default']
    ZBtn: typeof import('./components/ZBtn/index.vue')['default']
  }
}
