import { BlogCardProps } from "@/type";

export const BlogListData: BlogCardProps[] = [
  {
    id: "1",
    title: "test标题",
    content: "test内容",
    publishTime: "2021-01-01",
    lastUpdateTime: "2021-01-01",
    tags: ["test"],
    category: "test",
    cover: "test",
    byteNum: "100",
    commentNum: "100",
  },
  {
    id: "2",
    title: "test标题2",
    content: "test内容2",
    publishTime: "2021-01-01",
    lastUpdateTime: "2021-01-01",
    tags: ["test"],
    category: "test",
    cover: "test",
    byteNum: "100",
    commentNum: "100",
  },
  {
    id: "3",
    title: "test标题3",
    content: "test内容3",
    publishTime: "2021-01-01",
    lastUpdateTime: "2021-01-01",
    tags: ["test"],
    category: "test",
    cover: "test",
    byteNum: "100",
    commentNum: "100",
  },
  {
    id: "4",
    title: "test标题4",
    content: "test内容4",
    publishTime: "2021-01-01",
    lastUpdateTime: "2021-01-01",
    tags: ["test"],
    category: "test",
    cover: "test",
    byteNum: "100",
    commentNum: "100",
  },
  {
    id: "5",
    title: "test标题5",
    content: "test内容5",
    publishTime: "2021-01-01",
    lastUpdateTime: "2021-01-01",
    tags: ["test"],
    category: "test",
    cover: "test",
    byteNum: "100",
    commentNum: "100",
  },
]