/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Answer */
        post: operations["get_answer_ai_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chat-chunk-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Chunk Stream */
        post: operations["chat_chunk_stream_ai_chat_chunk_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chat_stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Answer Stream */
        post: operations["get_answer_stream_ai_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Image */
        post: operations["generate_image_ai_generate_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/read-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Image */
        post: operations["generate_image_ai_read_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description 登出：从 cookie 或 header 获取 token 并加入黑名单
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/qq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Qq */
        post: operations["qq_auth_qq_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description 刷新 access_token
         *     优先从 cookie 中读取 refresh_token，如果没有则从 header 读取
         */
        post: operations["refresh_token_auth_refresh_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset_password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset_password/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Reset Password */
        post: operations["request_reset_password_auth_reset_password_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/base/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Base Info
         * @description 获取博客的统计信息，包括文章数、种类数、标签数和总浏览量。
         */
        get: operations["base_info_base__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/base/blog/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 博客种类列表
         * @description 获取博客的种类列表
         */
        get: operations["get_blog_category_base_blog_category_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/base/blog/tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 博客tag列表
         * @description 获取博客的tag列表
         */
        get: operations["get_tag_list_base_blog_tag_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blogs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blogs Paginated
         * @description 分页获取博客列表
         *
         *     Args:
         *         page (int, optional): 页码. Defaults to 1.
         *         page_size (int, optional): 每页显示数量. Defaults to 10.
         *         blog_manager (BlogManager, optional): 博客管理对象. Defaults to Depends(get_blog_manager).
         *
         *     Returns:
         *         dict: 包含分页信息的字典
         */
        get: operations["get_blogs_paginated_blogs__get"];
        put?: never;
        /**
         * Create Blog
         * @description 创建新的博客
         *
         *     Args:
         *         blog (Blog): 新博客的数据模型
         *
         *     Returns:
         *         dict: 包含新博客 ID 的字典
         */
        post: operations["create_blog_blogs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blogs/{blog_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blog
         * @description 获取指定 ID 的博客
         *
         *     Args:
         *         blog_id (str): 博客的 ID
         *
         *     Returns:
         *         Blog: 博客对象，如果不存在则抛出 404 错误
         */
        get: operations["get_blog_blogs__blog_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Blog
         * @description 删除指定 ID 的博客
         *
         *     Args:
         *         blog_id (str): 博客的 ID
         *
         *     Returns:
         *         dict: 包含删除成功消息的字典
         */
        delete: operations["delete_blog_blogs__blog_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file/image/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_file_image_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file/video/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Video */
        post: operations["upload_video_file_video_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resources */
        get: operations["list_resources_resource__get"];
        put?: never;
        /** Create Resource */
        post: operations["create_resource_resource__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resource */
        get: operations["get_resource_resource__resource_id__get"];
        /** Update Resource */
        put: operations["update_resource_resource__resource_id__put"];
        post?: never;
        /** Delete Resource */
        delete: operations["delete_resource_resource__resource_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_role__get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_role__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Role */
        get: operations["get_role_role__role_id__get"];
        /** Update Role */
        put: operations["update_role_role__role_id__put"];
        post?: never;
        /** Delete Role */
        delete: operations["delete_role_role__role_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role/{role_id}/bind_resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind Resources */
        post: operations["bind_resources_role__role_id__bind_resources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users Paginated
         * @description 分页获取用户列表
         *
         *     Args:
         *         page (int, optional): 页码. Defaults to 1.
         *         page_size (int, optional): 每页显示数量. Defaults to 10.
         *         user_manager (UserManager, optional): 用户管理对象. Defaults to Depends(get_user_manager).
         *
         *     Returns:
         *         dict: 包含分页信息的字典
         */
        get: operations["get_users_paginated_user__get"];
        put?: never;
        /**
         * Create User
         * @description 创建新的用户
         *
         *     Args:
         *         user (User): 新用户的数据模型
         *
         *     Returns:
         *         dict: 包含新用户 ID 的字典
         */
        post: operations["create_user_user__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description 获取当前登录用户的信息
         *
         *     Args:
         *         current_user (User): 从 token 中解析出的当前用户
         *
         *     Returns:
         *         dict: 包含用户信息的响应
         */
        get: operations["get_current_user_info_user_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description 获取指定 ID 的用户
         *
         *     Args:
         *         user_id (str): 用户的 ID
         *
         *     Returns:
         *         User: 用户对象，如果不存在则抛出 404 错误
         */
        get: operations["get_user_user__user_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description 停用指定 ID 的用户
         *
         *     Args:
         *         user_id (str): 用户的 ID
         *
         *     Returns:
         *         dict: 包含停用成功消息的字典
         */
        delete: operations["delete_user_user__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponse[AuthSession] */
        ApiResponse_AuthSession_: {
            /** Code */
            code: number | string;
            data?: components["schemas"]["AuthSession"] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[BlogCreateResult] */
        ApiResponse_BlogCreateResult_: {
            /** Code */
            code: number | string;
            data?: components["schemas"]["BlogCreateResult"] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[BlogDetail] */
        ApiResponse_BlogDetail_: {
            /** Code */
            code: number | string;
            data?: components["schemas"]["BlogDetail"] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[BlogPage] */
        ApiResponse_BlogPage_: {
            /** Code */
            code: number | string;
            data?: components["schemas"]["BlogPage"] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[BlogStats] */
        ApiResponse_BlogStats_: {
            /** Code */
            code: number | string;
            data?: components["schemas"]["BlogStats"] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[List[Category]] */
        ApiResponse_List_Category__: {
            /** Code */
            code: number | string;
            /** Data */
            data?: components["schemas"]["Category"][] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[List[TagBase]] */
        ApiResponse_List_TagBase__: {
            /** Code */
            code: number | string;
            /** Data */
            data?: components["schemas"]["TagBase"][] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[NoneType] */
        ApiResponse_NoneType_: {
            /** Code */
            code: number | string;
            /** Data */
            data?: null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[UserCreateResult] */
        ApiResponse_UserCreateResult_: {
            /** Code */
            code: number | string;
            data?: components["schemas"]["UserCreateResult"] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[UserPage] */
        ApiResponse_UserPage_: {
            /** Code */
            code: number | string;
            data?: components["schemas"]["UserPage"] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[UserPublic] */
        ApiResponse_UserPublic_: {
            /** Code */
            code: number | string;
            data?: components["schemas"]["UserPublic"] | null;
            /** Msg */
            msg: string;
        };
        /** ApiResponse[bool] */
        ApiResponse_bool_: {
            /** Code */
            code: number | string;
            /** Data */
            data?: boolean | null;
            /** Msg */
            msg: string;
        };
        /** AuthSession */
        AuthSession: {
            /** Access Token */
            access_token?: string | null;
            /** Access Token Expire */
            access_token_expire?: string | null;
            /** Id */
            id?: number | null;
            /** Refresh Token */
            refresh_token?: string | null;
            /** Refresh Token Expire */
            refresh_token_expire?: string | null;
        };
        /** BindResourcesModel */
        BindResourcesModel: {
            /** Resource Ids */
            resource_ids: number[];
        };
        /** BlogBase */
        BlogBase: {
            /**
             * Abstract
             * @description 文章摘要
             */
            abstract: string;
            /**
             * Author
             * @description 作者
             * @default zxy
             */
            author: string | null;
            /**
             * Byte Num
             * @description 评论次数
             * @default 0
             */
            byte_num: number;
            /**
             * Category
             * @description 分类
             */
            category?: number | null;
            /**
             * Comment Num
             * @description 评论次数
             * @default 0
             */
            comment_num: number;
            /**
             * Id
             * @description 博客的唯一标识符
             */
            id?: number;
            /**
             * Tag
             * @description 标签
             * @default []
             */
            tag: number[] | null;
            /**
             * Title
             * @description 博客标题
             */
            title: string;
            /**
             * Updated At
             * Format: date-time
             * @description 更新时间
             */
            updated_at?: string;
            /**
             * View Num
             * @description 浏览次数
             * @default 0
             */
            view_num: number;
        };
        /** BlogCreate */
        BlogCreate: {
            /**
             * Abstract
             * @description 文章摘要
             */
            abstract: string;
            /**
             * Author
             * @description 作者
             * @default zxy
             */
            author: string | null;
            /**
             * Category
             * @description 分类
             */
            category: number;
            /**
             * Content
             * @description 博客内容
             */
            content: string;
            /**
             * Created At
             * Format: date-time
             * @description 创建时间
             */
            created_at?: string;
            /**
             * Id
             * @description 博客的唯一标识符
             */
            id?: number | null;
            /**
             * Tag
             * @description 文章标签（可以是已有标签ID或新增标签）
             */
            tag: (number | components["schemas"]["TagNew"])[];
            /**
             * Title
             * @description 博客标题
             */
            title: string;
            /**
             * Updated At
             * Format: date-time
             * @description 更新时间
             */
            updated_at?: string;
        };
        /** BlogCreateResult */
        BlogCreateResult: {
            /**
             * Id
             * @description 新建博客 ID
             */
            id: number;
        };
        /** BlogDetail */
        BlogDetail: {
            /**
             * Abstract
             * @description 文章摘要
             */
            abstract: string;
            /**
             * Author
             * @description 作者
             * @default zxy
             */
            author: string | null;
            /**
             * Byte Num
             * @description 评论次数
             * @default 0
             */
            byte_num: number;
            /**
             * Category
             * @description 分类
             */
            category?: number | null;
            /**
             * Comment Num
             * @description 评论次数
             * @default 0
             */
            comment_num: number;
            /**
             * Content
             * @description 博客内容
             */
            content: string;
            /**
             * Created At
             * Format: date-time
             * @description 创建时间
             */
            created_at?: string;
            /**
             * Id
             * @description 博客的唯一标识符
             */
            id?: number;
            /**
             * Tag
             * @description 标签
             * @default []
             */
            tag: number[] | null;
            /**
             * Title
             * @description 博客标题
             */
            title: string;
            /**
             * Updated At
             * Format: date-time
             * @description 更新时间
             */
            updated_at?: string;
            /**
             * View Num
             * @description 浏览次数
             * @default 0
             */
            view_num: number;
        };
        /** BlogPage */
        BlogPage: {
            /**
             * List
             * @description 当前页博客列表
             */
            list?: components["schemas"]["BlogBase"][];
            /**
             * Page
             * @description 当前页码
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             */
            page_size: number;
            /**
             * Total
             * @description 总条数
             */
            total: number;
        };
        /** BlogStats */
        BlogStats: {
            /**
             * Blog Count
             * @description 博客文章的总数量
             * @example 100
             */
            blog_count: number;
            /**
             * Category Count
             * @description 博客种类的总数量
             * @example 10
             */
            category_count: number;
            /**
             * Tag Count
             * @description 博客标签的总数量
             * @example 20
             */
            tag_count: number;
            /**
             * Total View Num
             * @description 所有博客的总浏览量，默认为0
             * @default 0
             * @example 5000
             */
            total_view_num: number;
        };
        /** Body_upload_image_file_image_upload_post */
        Body_upload_image_file_image_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_video_file_video_upload_post */
        Body_upload_video_file_video_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Category */
        Category: {
            /**
             * Id
             * @description 分类 ID
             */
            id: number;
            /**
             * Name
             * @description 分类名称
             */
            name: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Image Url */
            image_url?: string | null;
            /** Question */
            question: string;
            /**
             * Session Id
             * @default 1
             */
            session_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginModel */
        LoginModel: {
            /** Password */
            password: string;
            /** Username */
            username: string | null;
        };
        /** QQModel */
        QQModel: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
        };
        /** RegisterModel */
        RegisterModel: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
            /** Phone */
            phone: string | null;
        };
        /** ResetPasswordModel */
        ResetPasswordModel: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ResourceCreateModel */
        ResourceCreateModel: {
            /** Code */
            code: string;
            /**
             * Description
             * @default
             */
            description: string | null;
            /** Name */
            name: string;
            /**
             * Path
             * @default
             */
            path: string | null;
            /** Type */
            type: string;
        };
        /** ResourceUpdateModel */
        ResourceUpdateModel: {
            /** Code */
            code: string | null;
            /** Description */
            description: string | null;
            /** Name */
            name: string | null;
            /** Path */
            path: string | null;
            /** Type */
            type: string | null;
        };
        /** RoleCreateModel */
        RoleCreateModel: {
            /** Code */
            code: string;
            /**
             * Description
             * @default
             */
            description: string | null;
            /** Name */
            name: string;
        };
        /** RoleUpdateModel */
        RoleUpdateModel: {
            /** Code */
            code: string | null;
            /** Description */
            description: string | null;
            /** Name */
            name: string | null;
        };
        /** TagBase */
        TagBase: {
            /**
             * Id
             * @description 标签 ID
             */
            id: number;
            /**
             * Name
             * @description 标签名称
             */
            name: string;
        };
        /** TagNew */
        TagNew: {
            /**
             * Name
             * @description 新增标签的名称
             */
            name: string;
        };
        /** User */
        User: {
            /**
             * Age
             * @description 年龄
             */
            age: number;
            /**
             * Birth Day
             * Format: date
             * @description 出生日期，格式为 YYYY-MM-DD
             */
            birth_day: string;
            /**
             * Create Time
             * @description 创建时间
             */
            create_time?: string | null;
            /**
             * Email
             * @description 邮箱
             */
            email: string;
            /**
             * Id
             * @description 用户的唯一标识符，自增主键
             */
            id?: number | null;
            /**
             * Name
             * @description 昵称
             */
            name: string;
            /**
             * Password
             * @description 密码
             */
            password: string;
            /**
             * Phone
             * @description 手机号
             */
            phone: string;
            /**
             * Sex
             * @description 性别
             */
            sex: number;
            /**
             * Status
             * @description 用户是否启用，默认启用
             * @default true
             */
            status: boolean;
        };
        /** UserCreateResult */
        UserCreateResult: {
            /**
             * Id
             * @description 新建用户 ID
             */
            id?: number | null;
        };
        /** UserPage */
        UserPage: {
            /**
             * List
             * @description 当前页用户列表
             */
            list?: components["schemas"]["UserPublic"][];
            /**
             * Page
             * @description 当前页码
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             */
            page_size: number;
            /**
             * Total
             * @description 总条数
             */
            total: number;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Age
             * @description 年龄
             */
            age: number;
            /**
             * Birth Day
             * Format: date
             * @description 出生日期，格式为 YYYY-MM-DD
             */
            birth_day: string;
            /**
             * Create Time
             * @description 创建时间
             */
            create_time?: string | null;
            /**
             * Email
             * @description 邮箱
             */
            email: string;
            /**
             * Id
             * @description 用户的唯一标识符，自增主键
             */
            id?: number | null;
            /**
             * Name
             * @description 昵称
             */
            name: string;
            /**
             * Phone
             * @description 手机号
             */
            phone: string;
            /**
             * Resources
             * @description 用户资源权限
             */
            resources?: {
                [key: string]: unknown;
            }[];
            /**
             * Roles
             * @description 用户角色
             */
            roles?: {
                [key: string]: unknown;
            }[];
            /**
             * Sex
             * @description 性别
             */
            sex: number;
            /**
             * Status
             * @description 用户是否启用，默认启用
             * @default true
             */
            status: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_answer_ai_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chunk_stream_ai_chat_chunk_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_answer_stream_ai_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_image_ai_generate_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_image_ai_read_image_post: {
        parameters: {
            query: {
                uri: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AuthSession_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    qq_auth_qq_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QQModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_auth_refresh_token_post: {
        parameters: {
            query?: never;
            header?: {
                "refresh-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AuthSession_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AuthSession_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_reset_password_auth_reset_password_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    base_info_base__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_BlogStats_"];
                };
            };
        };
    };
    get_blog_category_base_blog_category_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_List_Category__"];
                };
            };
        };
    };
    get_tag_list_base_blog_tag_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_List_TagBase__"];
                };
            };
        };
    };
    get_blogs_paginated_blogs__get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_BlogPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_blog_blogs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_BlogCreateResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blog_blogs__blog_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blog_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_BlogDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_blog_blogs__blog_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_file_image_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_file_image_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_video_file_video_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_video_file_video_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resources_resource__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resource_resource__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceCreateModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resource_resource__resource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resource_resource__resource_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceUpdateModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resource_resource__resource_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_role__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_role_role__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreateModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_role_role__role_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_role__role_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdateModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_role__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_resources_role__role_id__bind_resources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindResourcesModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_users_paginated_user__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UserPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_user__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UserCreateResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_user_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UserPublic_"];
                };
            };
        };
    };
    get_user_user__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UserPublic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_user__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_bool_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
