/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogCard: typeof import('./src/components/BlogCard/index.vue')['default']
    CatalogCard: typeof import('./src/components/CatalogCard/index.vue')['default']
    CatalogItem: typeof import('./src/components/CatalogCard/CatalogItem/index.vue')['default']
    ChannelCard: typeof import('./src/components/ChannelCard/index.vue')['default']
    CutomBtn: typeof import('./src/components/CutomBtn.vue')['default']
    DIalogCard: typeof import('./src/components/DIalogCard/index.vue')['default']
    ElTree: typeof import('element-plus/es')['ElTree']
    LanguageSwitch: typeof import('./src/components/LanguageSwitch/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfInfoCard: typeof import('./src/components/SelfInfoCard/index.vue')['default']
    Tag: typeof import('./src/components/Tag/index.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch/index.vue')['default']
    WeatherCard: typeof import('./src/components/WeatherCard/index.vue')['default']
    ZBtn: typeof import('./src/components/ZBtn/index.vue')['default']
  }
}
